### ISSUE TITLE
Describe the report types being used?

### ISSUE THREAD

**Issue by jasonbrent** [AnykeyNL/SynthesiaKomplete#1]
Trying to kludge this together for MacOS using hidapi -- you write to reports[3] for initialization, then reports[2] for data. Can you further define what those report types are? It looks like pywinusb.hid.send() supports auto sending to _output_report or _feature_report based on __report_kind for the 'report' item in your list. Unfortunately I do not have a windows machine to quickly test this myself.

**Comment by AnykeyNL** [comment]
I have a MAC here as well, will try to do some testing on it and modify it to make it platform independent.
(is possible)

**Comment by jasonbrent** [comment]
On Mac, it seems that the hid commands simply don't make it out. I've tried
going all the way down to writing C and IOKit to access it directly with no
luck. Hidapi and cython-hidapi  (as well as PyUSB) all talk to the IOKit
interface on Mac. Hidapi, otherwise, is platform agnostic. I was able to
use cython-hidapi on Windows to map out the following control from another
post i made that you may find useful

Without an external hardware usb analyzer available, I'm at a loss on
identifying why I can't seem to get hid writes to the device under macos.
That said, there clearly has to be a way as Komplete Kontrol does it and
they don't have a custom kernel module loaded for specialized access.

One other piece, you don't need to disable the light strip in KK software
depending on how one writes the data. Kk itself simply always sends a new
0x82 command to set the lights after every key press on the keybed.

Lastly, the actual key press outputs, including the various control keys on
the device, all send their data via usb interrupt which is not available
via hid interfaces. I stopped short of seeing if I could read keypresses
from the keyboard with pywinusb the other evening.


:
 up on chasing down why I can't write to the device from MacOS for now, but
I was able to spend some time with the device and an analyzer.

Commands on the keyboard via USB so far... work in progress.

0xa0 - Seems to be overall device state/Mode Sending just 0xa0 initializes
the device and keyboard light control works.
0xa0 0xd9 0x00 - sets the device to "midi" mode? Light control of Transport
controls works, keyboard doesn't.
0xa0 0xd8 0x00 - seems to be the same as previous
0xa4 - Unknown (sets internal states?)
0xa6 - Unknown

0xe0 - addresses the scribble strip. 3 Rows, addressable by the 3rd byte in
the sequence (0x00 = top row, 0x01, middle row, 0x02, bottom row)

0x80 - Byte array that controls the brightness for each of the keys in the
following order:
Shift, Scale, Arp, Loop, RWD, FWD, PLAY, REC, STOP, Left Arrow, Right
Arrow, Browse, White Up Button, Instance, White Down Button, Back, Black Up
Arrow, Enter, Black Left Arrow, Black Down Arrow, Black Right Arrow. There
is a 4 byte pad at the end.
Example: 0x80 0xFF would turn on only the "SHIFT" key to full brightness.
0x80 0x00 0xFF would turn the SCALE key to full brightness...

0x82 - Controls the RGBs on the Keys. 3 bytes per key, with a value of
0-255 for each of R,G,B.

Example: 0x82 0xFF 0xFF 0xFF would turn the left most key full white.

It is possible to gain full control of the keyboard, lights, scribble
strip, and transport controls. Just requires some reverse engineering and
some code writing.
